#!/bin/sh
set -e

[ "${PKG_UPGRADE}" = "1" ] && exit 0

rm -f /opt/bin/tg-ws-proxy
rm -f /opt/etc/init.d/S99tg-ws-proxy
rm -rf /opt/etc/tg-ws-proxy
rm -f /opt/var/log/tg-ws-proxy.log

echo "tg-ws-proxy removed"
